<?php
/**
 * wallee Magento 2
 *
 * This Magento 2 extension enables to process payments with wallee (https://www.wallee.com/).
 *
 * @package Wallee_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/** @var $block \Wallee\Payment\Block\DeviceSession */
?>
<script type="text/x-magento-init">
{
    "*": {
        "Wallee_Payment/js/wallee-device": {
            "scriptUrl" : "<?=$block->escapeHtml($block->getScriptUrl())?>",
            "identifierUrl" : "<?=$block->escapeHtml($block->getSessionIdentifierUrl())?>"
        }
    }
}
</script>