<?php
/**
 * wallee Magento 2
 *
 * This Magento 2 extension enables to process payments with wallee (https://www.wallee.com/).
 *
 * @package Wallee_Payment
 * @author wallee AG (http://www.wallee.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */
/**
 * @formatter:off
 */

/** @var $block \Wallee\Payment\Block\Method\Info */
?>

<dl class="payment-method <?=$block->escapeHtml($block->getMethodCode())?>">
    <dt class="title"><?=$block->escapeHtml($block->getMethod()->getTitle())?></dt>
    <?php if ($block->isInvoiceDownloadAllowed()) : ?>
        <dd class="content">
            <a href="<?=$block->escapeHtml($block->getInvoiceDownloadUrl())?>"><?=$block->escapeHtml(\__('Download Invoice'))?></a>
        </dd>
    <?php endif; ?>
    <?php if ($block->isPackingSlipDownloadAllowed()) : ?>
        <dd class="content">
            <a href="<?=$block->escapeHtml($block->getPackingSlipDownloadUrl())?>"><?=$block->escapeHtml(\__('Download Packing Slip'))?></a>
        </dd>
    <?php endif; ?>
</dl>