<?php
/**
 * Wallee Magento 2
 *
 * This Magento 2 extension enables to process payments with Wallee (https://www.wallee.com/).
 *
 * @package Wallee_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */
/**
 * @formatter:off
 */

/** @var $block \Wallee\Payment\Block\Method\Form */
$code = $block->escapeHtml($block->getMethodCode());
$tokens = $block->getTokens();
?>

<fieldset class="admin__fieldset payment-method" id="payment_form_<?=$code?>" style="display:none">
	<div class="admin__field">
		<div class="admin__field-control">
    		<?=$block->escapeHtml(\__('A charge flow will be used to process the payment.'))?>
		</div>
    </div>
    <?php if (! empty($tokens)) : ?>
		<div class="admin__field _required">
            <label class="admin__field-label" for="<?=$code?>_token">
                <span><?=$block->escapeHtml(\__('Token:'))?></span>
            </label>
            <div class="admin__field-control">
                <select id="<?=$code?>_token" name="payment[<?=$block->escapeHtml($block->getTransportName())?>]" class="required-entry admin__control-select">
                    <option value=""></option>
                    <?php foreach ($tokens as $token) : ?>
                        <option value="<?=$block->escapeHtml($token->getId())?>"
                        <?=($token->getId() == $block->getInfoData($block->getTransportName())) ? ' selected="selected"' : '';?>>
                            <?=$block->escapeHtml($token->getName())?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <div>
                	<small><?=$block->escapeHtml(\__('The customer can be charged by using an existing token. If left empty, no token is used.'))?></small>
            	</div>
            </div>
        </div>
    <?php endif; ?>
</fieldset>