<?php
/**
 * wallee Magento 2
 *
 * This Magento 2 extension enables to process payments with wallee (https://www.wallee.com/).
 *
 * @package Wallee_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */
/**
 * @formatter:off
 */

/** @var $block \Wallee\Payment\Block\Method\Info */
?>

<div class="admin__page-section-item-content">
	<table class="data-table admin__table-secondary">
		<tr>
			<th><?=$block->escapeHtml(\__('Payment Method'))?></th>
			<td><?=$block->escapeHtml($block->getMethod()->getPaymentMethodConfiguration()->getConfigurationName()) ?></td>
		</tr>
    	<?php $imageUrl = $block->getImageUrl(); if ($imageUrl) : ?>
    		<tr>
    			<th></th>
    			<td><img src="<?=$block->escapeHtml($imageUrl)?>" width="50" /></td>
    		</tr>
    	<?php endif; ?>
    	<?php if ($block->getTransaction()) : ?>
    		<tr>
    			<th><?=$block->escapeHtml(\__('Transaction State'))?></th>
    			<td><?=$block->escapeHtml($block->getTransactionState()) ?></td>
    		</tr>
    		<?php if ($block->getTransaction()->getFailureReason() != null) : ?>
        		<tr>
        			<th><?=$block->escapeHtml(\__('Failure Reason'))?></th>
        			<td><?=$block->escapeHtml($block->translate($block->getTransaction()->getFailureReason())) ?></td>
        		</tr>
    		<?php endif; ?>
    		<tr>
    			<th><?=$block->escapeHtml(\__('Authorization Amount'))?></th>
    			<td><?=$block->escapeHtml($block->formatAmount($block->getTransaction()->getAuthorizationAmount())) ?></td>
    		</tr>
    		<tr>
    			<th><?=$block->escapeHtml(\__('Transaction'))?></th>
    			<td><a target="_blank" href="<?=$block->escapeHtml($block->getTransactionUrl())?>"><?=$block->escapeHtml(\__('View in wallee'))?></a></td>
    		</tr>
    	<?php endif; ?>
        <?php if ($block->isInvoice() && $block->isInvoiceDownloadAllowed()) : ?>
			<tr>
    			<th><?=$block->escapeHtml(\__('Invoice'))?></th>
    			<td><a href="<?=$block->escapeHtml($block->getInvoiceDownloadUrl())?>"><?=$block->escapeHtml(\__('Download Invoice'))?></a></td>
			</tr>
        <?php endif;?>
        <?php if ($block->isShipment() && $block->isPackingSlipDownloadAllowed()) : ?>
			<tr>
    			<th><?=$block->escapeHtml(\__('Packing Slip'))?></th>
    			<td><a href="<?=$block->escapeHtml($block->getPackingSlipDownloadUrl())?>"><?=$block->escapeHtml(\__('Download Packing Slip'))?></a></td>
			</tr>
        <?php endif;?>
        <?php if ($block->isCreditmemo() && $block->isRefundDownloadAllowed()) : ?>
			<tr>
    			<th><?=$block->escapeHtml(\__('Refund'))?></th>
    			<td><a href="<?=$block->escapeHtml($block->getRefundDownloadUrl())?>"><?=$block->escapeHtml(\__('Download Refund'))?></a></td>
			</tr>
        <?php endif;?>
	</table>

	<?php foreach ($block->getGroupedLabels() as $group) : ?>
		<div class="wallee-label-container">
    		<a><?=$block->escapeHtml($block->translate($group->getName()))?></a>
    		<table class="data-table admin__table-secondary">
    			<?php foreach ($group->getLabels() as $label) : ?>
            		<tr>
            			<th><?=$block->escapeHtml($block->translate($label->getName()))?></th>
            			<td><?=$block->escapeHtml($label->getValue()) ?></td>
            		</tr>
    			<?php endforeach; ?>
    		</table>
		</div>
	<?php endforeach; ?>
</div>