<?php
/**
 * wallee Magento 2
 *
 * This Magento 2 extension enables to process payments with wallee (https://www.wallee.com/).
 *
 * @package Wallee_Payment
 * @author wallee AG (http://www.wallee.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */
/**
 * @formatter:off
 */

/** @var $block \Wallee\Payment\Block\Adminhtml\Sales\Order\Invoice\View */
?>

<?php if ($block->isCapturePending()) : ?>
	<div class="messages">
		<div class="message message-warning warning">
			<?=$block->escapeHtml(\__('The capture has been requested but could not be completed yet. The invoice will be updated, as soon as the capture is done.'))?>
		</div>
	</div>
<?php endif; ?>