<?php
/**
 * wallee Magento 2
 *
 * This Magento 2 extension enables to process payments with wallee (https://www.wallee.com/).
 *
 * @package Wallee_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */
/**
 * @formatter:off
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<script>
    require([
        "Magento_Ui/js/modal/confirm",
        "prototype"
    ], function(confirm){
        tokenControl = {
            reload: function (urlParams) {
                if (!urlParams) {
                    urlParams = '';
                }
                var url = <?=$block->escapeJs($block->escapeUrl($block->getJsObjectName()))?>.url + '?ajax=true' + urlParams;
                new Ajax.Updater(
                    <?=$block->escapeJs($block->escapeHtml($block->getJsObjectName()))?>.containerId,
                    url, {
                        parameters: {form_key: FORM_KEY},
                        onComplete: <?=$block->escapeJs($block->escapeHtml($block->getJsObjectName()))?>.initGrid.bind(<?=$block->escapeJs($block->escapeHtml($block->getJsObjectName()))?>),
                        evalScripts:true
                    }
                );
        	},

            removeToken: function (tokenId) {
                var self = this;

                confirm({
                    content: '<?=$block->escapeJs($block->escapeHtml(\__('Are you sure you want to remove this token?')))?>',
                    actions: {
                        confirm: function () {
                            self.reload('&delete=' + tokenId);
                        }
                    }
                });
            }
        }
    });
</script>
